ALTER TABLE products ADD COLUMN IF NOT EXISTS cost_price NUMERIC(10,2);
ALTER TABLE products ADD COLUMN IF NOT EXISTS production_date DATE;
ALTER TABLE products ADD COLUMN IF NOT EXISTS shipping_days INTEGER;
ALTER TABLE products ADD COLUMN IF NOT EXISTS shipping_fee NUMERIC(10,2);
ALTER TABLE products ADD COLUMN IF NOT EXISTS remarks TEXT DEFAULT '';
