-- Create rejectedd_products table to store products marked as "暫不考慮"
create table if not exists public.rejectedd_products (
  id                      uuid primary key default gen_random_uuid(),
  original_product_id     uuid,
  title                   text,
  description             text,
  description_html        text,
  tags                    text[],
  price                   numeric,
  compare_at_price        numeric,
  collection              text,
  status                  text,
  image_url               text,
  images                  jsonb,
  shopify_product_id      text,
  source                  text,
  synced_at               timestamptz,
  color                   text,
  factory_id              uuid,
  factories_display_name  text,
  cost_price              numeric,
  sale_price              numeric,
  production_lead_time    integer,
  shipping_days           integer,
  shipping_fee            numeric,
  total_lead_time         integer,
  bwf_master_id           uuid,
  remarks                 text,
  category                text,
  level1_category         text,
  level2_category         text,
  production_time         text,
  material                text,
  model                   text,
  specifications          text,
  delivery_term_id        uuid,
  delivery_term_name      text,
  in_stock                boolean,
  customize               text,
  dimension_l_mm          integer,
  dimension_w_mm          integer,
  dimension_h_mm          integer,
  product_sku             text,
  variants                jsonb,
  rejection_source        text default 'listed_products',
  rejected_at             timestamptz not null default now()
);

-- Index for looking up by original product id
create index if not exists rejectedd_products_original_product_id_idx
  on public.rejectedd_products (original_product_id);
